version: '3.5'

services:
  node1:
    build: ./server
    depends_on:
      - redis
  node2:
    build: ./server
    depends_on:
      - redis
  node3:
    build: ./server
    depends_on:
      - redis
  nginx:
    image: nginx
    ports:
      - 3000:3000
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
  redis:
    image: redis
